# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import items_pb2 as items__pb2


class ItemMasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetItem = channel.unary_unary(
                '/ItemMaster/GetItem',
                request_serializer=items__pb2.GetItemRequest.SerializeToString,
                response_deserializer=items__pb2.GetItemResponse.FromString,
                )
        self.AddItem = channel.unary_unary(
                '/ItemMaster/AddItem',
                request_serializer=items__pb2.AddItemRequest.SerializeToString,
                response_deserializer=items__pb2.AddItemResponse.FromString,
                )
        self.ChangeItem = channel.unary_unary(
                '/ItemMaster/ChangeItem',
                request_serializer=items__pb2.ChangeItemRequest.SerializeToString,
                response_deserializer=items__pb2.ChangeItemResponse.FromString,
                )
        self.RemoveItem = channel.unary_unary(
                '/ItemMaster/RemoveItem',
                request_serializer=items__pb2.RemoveItemRequest.SerializeToString,
                response_deserializer=items__pb2.RemoveItemResponse.FromString,
                )
        self.DisplayItem = channel.unary_unary(
                '/ItemMaster/DisplayItem',
                request_serializer=items__pb2.DisplayItemRequest.SerializeToString,
                response_deserializer=items__pb2.DisplayItemResponse.FromString,
                )
        self.CreateAccount = channel.unary_unary(
                '/ItemMaster/CreateAccount',
                request_serializer=items__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=items__pb2.CreateAccountResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/ItemMaster/Login',
                request_serializer=items__pb2.LoginRequest.SerializeToString,
                response_deserializer=items__pb2.LoginResponse.FromString,
                )
        self.Logout = channel.unary_unary(
                '/ItemMaster/Logout',
                request_serializer=items__pb2.LogoutRequest.SerializeToString,
                response_deserializer=items__pb2.LogoutResponse.FromString,
                )
        self.GetSellerRating = channel.unary_unary(
                '/ItemMaster/GetSellerRating',
                request_serializer=items__pb2.GetSellerRatingRequest.SerializeToString,
                response_deserializer=items__pb2.GetSellerRatingResponse.FromString,
                )


class ItemMasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetItem(self, request, context):
        """Get an item by id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplayItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemMasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=items__pb2.GetItemRequest.FromString,
                    response_serializer=items__pb2.GetItemResponse.SerializeToString,
            ),
            'AddItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AddItem,
                    request_deserializer=items__pb2.AddItemRequest.FromString,
                    response_serializer=items__pb2.AddItemResponse.SerializeToString,
            ),
            'ChangeItem': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeItem,
                    request_deserializer=items__pb2.ChangeItemRequest.FromString,
                    response_serializer=items__pb2.ChangeItemResponse.SerializeToString,
            ),
            'RemoveItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveItem,
                    request_deserializer=items__pb2.RemoveItemRequest.FromString,
                    response_serializer=items__pb2.RemoveItemResponse.SerializeToString,
            ),
            'DisplayItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplayItem,
                    request_deserializer=items__pb2.DisplayItemRequest.FromString,
                    response_serializer=items__pb2.DisplayItemResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=items__pb2.CreateAccountRequest.FromString,
                    response_serializer=items__pb2.CreateAccountResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=items__pb2.LoginRequest.FromString,
                    response_serializer=items__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=items__pb2.LogoutRequest.FromString,
                    response_serializer=items__pb2.LogoutResponse.SerializeToString,
            ),
            'GetSellerRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerRating,
                    request_deserializer=items__pb2.GetSellerRatingRequest.FromString,
                    response_serializer=items__pb2.GetSellerRatingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ItemMaster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ItemMaster(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ItemMaster/GetItem',
            items__pb2.GetItemRequest.SerializeToString,
            items__pb2.GetItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ItemMaster/AddItem',
            items__pb2.AddItemRequest.SerializeToString,
            items__pb2.AddItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ItemMaster/ChangeItem',
            items__pb2.ChangeItemRequest.SerializeToString,
            items__pb2.ChangeItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ItemMaster/RemoveItem',
            items__pb2.RemoveItemRequest.SerializeToString,
            items__pb2.RemoveItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisplayItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ItemMaster/DisplayItem',
            items__pb2.DisplayItemRequest.SerializeToString,
            items__pb2.DisplayItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ItemMaster/CreateAccount',
            items__pb2.CreateAccountRequest.SerializeToString,
            items__pb2.CreateAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ItemMaster/Login',
            items__pb2.LoginRequest.SerializeToString,
            items__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ItemMaster/Logout',
            items__pb2.LogoutRequest.SerializeToString,
            items__pb2.LogoutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSellerRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ItemMaster/GetSellerRating',
            items__pb2.GetSellerRatingRequest.SerializeToString,
            items__pb2.GetSellerRatingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
