# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import buyer_pb2 as buyer__pb2


class BuyerMasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchItemCart = channel.unary_unary(
                '/BuyerMaster/SearchItemCart',
                request_serializer=buyer__pb2.SearchItemCartRequest.SerializeToString,
                response_deserializer=buyer__pb2.SearchItemCartResponse.FromString,
                )
        self.AddToCart = channel.unary_unary(
                '/BuyerMaster/AddToCart',
                request_serializer=buyer__pb2.AddToCartRequest.SerializeToString,
                response_deserializer=buyer__pb2.AddToCartResponse.FromString,
                )
        self.RemoveItemFromShoppingCart = channel.unary_unary(
                '/BuyerMaster/RemoveItemFromShoppingCart',
                request_serializer=buyer__pb2.RemoveItemFromShoppingCartRequest.SerializeToString,
                response_deserializer=buyer__pb2.RemoveItemFromShoppingCartResponse.FromString,
                )
        self.ClearCart = channel.unary_unary(
                '/BuyerMaster/ClearCart',
                request_serializer=buyer__pb2.ClearCartRequest.SerializeToString,
                response_deserializer=buyer__pb2.ClearCartResponse.FromString,
                )
        self.DisplayCart = channel.unary_unary(
                '/BuyerMaster/DisplayCart',
                request_serializer=buyer__pb2.DisplayCartRequest.SerializeToString,
                response_deserializer=buyer__pb2.DisplayCartResponse.FromString,
                )
        self.CreateAccount = channel.unary_unary(
                '/BuyerMaster/CreateAccount',
                request_serializer=buyer__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=buyer__pb2.CreateAccountResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/BuyerMaster/Login',
                request_serializer=buyer__pb2.LoginRequest.SerializeToString,
                response_deserializer=buyer__pb2.LoginResponse.FromString,
                )
        self.Logout = channel.unary_unary(
                '/BuyerMaster/Logout',
                request_serializer=buyer__pb2.LogoutRequest.SerializeToString,
                response_deserializer=buyer__pb2.LogoutResponse.FromString,
                )
        self.MakePurchase = channel.unary_unary(
                '/BuyerMaster/MakePurchase',
                request_serializer=buyer__pb2.MakePurchaseRequest.SerializeToString,
                response_deserializer=buyer__pb2.MakePurchaseResponse.FromString,
                )
        self.ProvideFeedback = channel.unary_unary(
                '/BuyerMaster/ProvideFeedback',
                request_serializer=buyer__pb2.ProvideFeedbackRequest.SerializeToString,
                response_deserializer=buyer__pb2.ProvideFeedbackResponse.FromString,
                )
        self.GetSellerRating = channel.unary_unary(
                '/BuyerMaster/GetSellerRating',
                request_serializer=buyer__pb2.GetSellerRatingRequest.SerializeToString,
                response_deserializer=buyer__pb2.GetSellerRatingResponse.FromString,
                )
        self.GetBuyerHistory = channel.unary_unary(
                '/BuyerMaster/GetBuyerHistory',
                request_serializer=buyer__pb2.GetBuyerHistoryRequest.SerializeToString,
                response_deserializer=buyer__pb2.GetBuyerHistoryResponse.FromString,
                )


class BuyerMasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchItemCart(self, request, context):
        """Get an item by id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveItemFromShoppingCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplayCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakePurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvideFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuyerMasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchItemCart': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItemCart,
                    request_deserializer=buyer__pb2.SearchItemCartRequest.FromString,
                    response_serializer=buyer__pb2.SearchItemCartResponse.SerializeToString,
            ),
            'AddToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToCart,
                    request_deserializer=buyer__pb2.AddToCartRequest.FromString,
                    response_serializer=buyer__pb2.AddToCartResponse.SerializeToString,
            ),
            'RemoveItemFromShoppingCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveItemFromShoppingCart,
                    request_deserializer=buyer__pb2.RemoveItemFromShoppingCartRequest.FromString,
                    response_serializer=buyer__pb2.RemoveItemFromShoppingCartResponse.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=buyer__pb2.ClearCartRequest.FromString,
                    response_serializer=buyer__pb2.ClearCartResponse.SerializeToString,
            ),
            'DisplayCart': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplayCart,
                    request_deserializer=buyer__pb2.DisplayCartRequest.FromString,
                    response_serializer=buyer__pb2.DisplayCartResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=buyer__pb2.CreateAccountRequest.FromString,
                    response_serializer=buyer__pb2.CreateAccountResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=buyer__pb2.LoginRequest.FromString,
                    response_serializer=buyer__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=buyer__pb2.LogoutRequest.FromString,
                    response_serializer=buyer__pb2.LogoutResponse.SerializeToString,
            ),
            'MakePurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePurchase,
                    request_deserializer=buyer__pb2.MakePurchaseRequest.FromString,
                    response_serializer=buyer__pb2.MakePurchaseResponse.SerializeToString,
            ),
            'ProvideFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvideFeedback,
                    request_deserializer=buyer__pb2.ProvideFeedbackRequest.FromString,
                    response_serializer=buyer__pb2.ProvideFeedbackResponse.SerializeToString,
            ),
            'GetSellerRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerRating,
                    request_deserializer=buyer__pb2.GetSellerRatingRequest.FromString,
                    response_serializer=buyer__pb2.GetSellerRatingResponse.SerializeToString,
            ),
            'GetBuyerHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerHistory,
                    request_deserializer=buyer__pb2.GetBuyerHistoryRequest.FromString,
                    response_serializer=buyer__pb2.GetBuyerHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BuyerMaster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BuyerMaster(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchItemCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerMaster/SearchItemCart',
            buyer__pb2.SearchItemCartRequest.SerializeToString,
            buyer__pb2.SearchItemCartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerMaster/AddToCart',
            buyer__pb2.AddToCartRequest.SerializeToString,
            buyer__pb2.AddToCartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveItemFromShoppingCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerMaster/RemoveItemFromShoppingCart',
            buyer__pb2.RemoveItemFromShoppingCartRequest.SerializeToString,
            buyer__pb2.RemoveItemFromShoppingCartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerMaster/ClearCart',
            buyer__pb2.ClearCartRequest.SerializeToString,
            buyer__pb2.ClearCartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisplayCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerMaster/DisplayCart',
            buyer__pb2.DisplayCartRequest.SerializeToString,
            buyer__pb2.DisplayCartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerMaster/CreateAccount',
            buyer__pb2.CreateAccountRequest.SerializeToString,
            buyer__pb2.CreateAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerMaster/Login',
            buyer__pb2.LoginRequest.SerializeToString,
            buyer__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerMaster/Logout',
            buyer__pb2.LogoutRequest.SerializeToString,
            buyer__pb2.LogoutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MakePurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerMaster/MakePurchase',
            buyer__pb2.MakePurchaseRequest.SerializeToString,
            buyer__pb2.MakePurchaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProvideFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerMaster/ProvideFeedback',
            buyer__pb2.ProvideFeedbackRequest.SerializeToString,
            buyer__pb2.ProvideFeedbackResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSellerRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerMaster/GetSellerRating',
            buyer__pb2.GetSellerRatingRequest.SerializeToString,
            buyer__pb2.GetSellerRatingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBuyerHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerMaster/GetBuyerHistory',
            buyer__pb2.GetBuyerHistoryRequest.SerializeToString,
            buyer__pb2.GetBuyerHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
